Updated Read me for eq-google-slides-to-schema
ONSdigital/eq-google-slides-to-schema pull request #1
Opened 2017-02-24 13:46 UTC by yoganandkunche

Updated Read me for eq-google-slides-to-schema

python convert.py --presentation_id=1dBACWN8uOdznEpJHYL9zQQAiFoHyVe-eLVdJwc2ZGvw --out=mwss_4.json

2017-02-24 13:48 UTC, collisdigital commented
Please squash and sort out the line endings changes.

2017-03-01 14:00 UTC, benjefferies requested changes

2017-03-01 14:00 UTC, benjefferies commented on README.md
> +python /convert.py --presentation_id=[...] --out=survey.json
Shouldn't this be ./convert.py

2017-03-01 14:00 UTC, benjefferies commented on README.md
> +In order to extract content from the Slides into a schema some
Is it not better to one line this and let whatever is rendering it wrap?

2017-03-01 16:20 UTC, yoganandkunche commented on README.md
> +In order to extract content from the Slides into a schema some
out of scope for this PR

2017-03-01 16:22 UTC, benjefferies approved these changes

2017-03-01 16:32 UTC, merged